Repository MGastelluM/blockchain-project, pull requests merged in 2023-10, with the labels that each got.

#4 feat(): update package json
  db-level/package-lock.json
  db-level/package.json
  package-lock.json
  package.json
Labels: bug

#7 Create README.md
  README.md
Labels: documentation

#8 Mayor feats for get block by ID and menu
  db-level/db.js
  db-level/package.json
  functions/src/blockchain-core/chain.ts
  functions/src/blockchain-core/database_logic.ts
  index.ts
Labels: enhancement

#11 Readme.md UPDATE
  README.md
Labels: documentation

#10 BUG () database correctly being created upon new chain
  index.ts
Labels: bug

#13 Update README.md
  README.md
Labels: documentation
